FROM alpine:3.17.2

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata

RUN apk add --no-cache nodejs=18.14.2-r0 \
    && apk add --no-cache npm=9.1.2-r0 \
    && apk add --no-cache nginx=1.22.1-r0 \
    && apk add --no-cache gettext