FROM alpine:3.14.6

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata

RUN apk add --no-cache nodejs=14.19.0-r0 \
    && apk add --no-cache npm=7.17.0-r0 \
    && apk add --no-cache nginx=1.20.2-r1 \
    && apk add --no-cache gettext